version: '3.9'

services:
  budget-pg:
    container_name: budget_pg
    image: postgres:14.2-alpine
    restart: unless-stopped
    env_file:
      - api.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5441:5432'
    networks:
      - default

  budget-api:
    container_name: budget_api
    depends_on:
      - budget-pg
    image: budget/api:v${VERSION}
    restart: unless-stopped
    command: yarn dev
    env_file:
      - api.env
    ports:
      - '3000:3000'
    networks:
      - default

networks:
  default:
    name: budget-net
