# https://taskfile.dev

version: '3'

output: prefixed

vars:
  VERSION: $(awk '/version/{gsub(/("|",)/,"",$2);print $2};' source/package.json)

tasks:
  run:
    deps: [build]
    cmds:
      - VERSION={{.VERSION}} docker-compose up -d

  build:
    deps: [pull]
    cmds:
      - docker build -t budget/api:v{{.VERSION}} --target dependencies ./source

  pull:
    cmds:
      - cd source && git pull origin dev && cd ../

  logs:
    cmds:
      - docker-compose logs -f

  clean:
    cmds:
      - docker-compose down --rmi all --volumes
